// <auto-generated />
using System;
using HR.RenewalsAndLayoffs.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.RenewalsAndLayoffs.Data.Migrations
{
    [DbContext(typeof(HRContext))]
    [Migration("20230519214401_AddOtherKeysToEmployee")]
    partial class AddOtherKeysToEmployee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("HR.RenewalsAndLayoffs.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContractStatus")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("FingerPrint")
                        .HasColumnType("bit");

                    b.Property<int?>("FortiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiringType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Identification")
                        .HasColumnType("bit");

                    b.Property<string>("JobPosition")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonnelNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProofOfTaxSituation")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
