// <auto-generated />
using System;
using HR.RenewalsAndLayoffs.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.RenewalsAndLayoffs.Data.Migrations
{
    [DbContext(typeof(HRContext))]
    [Migration("20230519211443_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("HR.RenewalsAndLayoffs.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FingerPrint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiringType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobPosition")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProofOfTaxSituation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
